from typing import Tuple
import pygame
from utils import colors


TOWERS = {"source": 0, "auxiliary": 1, "destination": 2}
SOURCE_TOWER = 0
AUXILIARY_TOWER = 1
DESTINATION_TOWER = 2


MIN_DISKS = 3
"""Minimum number of disks"""
MAX_DISKS = 15
"""Maximum number of disks"""

DISK_WIDTH_MIN = 100
DISK_WIDTH_MAX = 200
DISK_HEIGHT_MAX = 30

DISK_SPEED = 500

BACKGROUND_COLOR = colors.WHITE

BOTTOM_DISK_COLOR = pygame.Color(50, 0, 200)
TOP_DISK_COLOR = pygame.Color(200, 0, 50)

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

OUTER_MARGIN = 50
INNER_GAP = 25

MENU_WIDTH = SCREEN_WIDTH - OUTER_MARGIN * 2
MENU_HEIGHT = 50

TOWER_HEIGHT = SCREEN_HEIGHT - OUTER_MARGIN * 2 - MENU_HEIGHT - INNER_GAP

TOWER_POSITIONS = (
    (OUTER_MARGIN * 1 + DISK_WIDTH_MAX * 0, SCREEN_HEIGHT - OUTER_MARGIN),
    (OUTER_MARGIN * 2 + DISK_WIDTH_MAX * 1, SCREEN_HEIGHT - OUTER_MARGIN),
    (OUTER_MARGIN * 3 + DISK_WIDTH_MAX * 2, SCREEN_HEIGHT - OUTER_MARGIN),
)
